pieces:
  - name: "warrior"
    sprites:
      white:
        - [ 0, 0 ]
        - [ 1, 0 ]
      black:
        - [ 2, 1 ]
        - [ 3, 1 ]
    # Two moves orthogonally
    moves:
      - [ 1, 0 ]
      - [ 2, 0 ]
      - [ 0, 1 ]
      - [ 0, 2 ]
      - [ 0, -1 ]
      - [ 0, -2 ]
      - [ -1, 0 ]
      - [ -2, 0 ]
  - name: "padwar"
    sprites:
      white:
        - [ 0, 1 ]
        - [ 1, 1 ]
      black:
        - [ 2, 4 ]
        - [ 3, 4 ]
    moves:
      # Two squares diagonally (row, col)
      - [ 1, 1 ]
      - [ 2, 2 ]
      - [ -1, 1 ]
      - [ -2, 2 ]
      - [ 1, -1 ]
      - [ 2, -2 ]
      - [ -1, -1 ]
      - [ -2, -2 ]
board:
  # Starting board positions
  white:
    - name: "warrior"
      position: [0, 0]
    - name: "padwar"
      position: [0, 1]
    - name: "padwar"
      position: [0, 8]
    - name: "warrior"
      position: [0, 9]
  black:
    - name: "warrior"
      position: [9, 0]
    - name: "padwar"
      position: [9, 1]
    - name: "padwar"
      position: [9, 8]
    - name: "warrior"
      position: [9, 9]
